source "https://rubygems.org"
gem "jekyll", "~> 4.0"
gem "liquid", "~> 4.0"  # Use Liquid 4.x to match Jekyll 4.x
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jemoji"
gem "jekyll-include-cache"
# gem "jekyll-remote-theme"
gem "webrick", "~> 1.9"